parameters:
- name: browser
  displayName: 'Browser for UI tests'
  type: string
  default: 'chrome'
  values:
  - chrome
  - firefox
  - edge

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: "0 21 * * *"
    displayName: "Nightly build"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
  - job: APITests
    displayName: 'Execute API Tests'
    steps:
      - task: UseDotNet@2
        inputs:
          version: '5.x'
          packageType: 'sdk'
      
      - task: UseDotNet@2
        inputs:
          version: '5.x'
          packageType: 'runtime'

      - script: dotnet restore TAF_Task/TAF_Task_API/TAF_Task_API.csproj
        displayName: 'Restore API Packages'

      - script: dotnet build TAF_Task/TAF_Task_API/TAF_Task_API.csproj --configuration $(buildConfiguration) --no-restore
        displayName: 'Build API Project'

      - script: dotnet test TAF_Task/TAF_Task_API/TAF_Task_API.csproj --configuration $(buildConfiguration) --no-restore --no-build --logger "trx;LogFileName=api_test_results.trx"
        displayName: 'Test API Project'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/api_test_results.trx'
        displayName: 'Publish API Test Results'
        
  - job: UITests
    displayName: 'Execute UI Tests'
    dependsOn: APITests
    condition: succeededOrFailed()
    steps:
      - task: UseDotNet@2
        inputs:
          version: '5.x'
          packageType: 'sdk'
      
      - task: UseDotNet@2
        inputs:
          version: '5.x'
          packageType: 'runtime'

      - script: dotnet restore TAF_Task/TAF_Task/TAF_Task.csproj
        displayName: 'Restore UI Packages'

      - script: dotnet build TAF_Task/TAF_Task/TAF_Task.csproj --configuration $(buildConfiguration) --no-restore
        displayName: 'Build UI Project'

      - script: dotnet test TAF_Task/TAF_Task/TAF_Task.csproj --configuration $(buildConfiguration) --no-restore --no-build --logger "trx;LogFileName=ui_test_results.trx" -e UI_TEST=true -e BROWSER=${{ parameters.browser }}
        displayName: 'Test UI Project'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/ui_test_results.trx'
        displayName: 'Publish UI Test Results'

      - upload: '**/screenshots'
        condition: succeeded()
        displayName: 'Upload Screenshots'
        artifact: Screenshots