parameters:
- name: browser
  displayName: 'Browser for UI tests'
  type: string
  default: 'chrome'
  values:
  - chrome
  - firefox
  - edge
  
trigger:
  branches:
    include:
      - main

pr:
  - main

schedules:
  - cron: "0 21 * * *"
    displayName: "Nightly build"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:
  - job: Setup_and_Test
    displayName: 'Setup, Build and Test API'
    steps:
      - task: UseDotNet@2
        inputs:
          version: '5.x'
          packageType: 'sdk'
      
      - task: UseDotNet@2
        inputs:
          version: '5.x'
          packageType: 'runtime'
      
      - script: dotnet restore ./TAF_Task_API/TAF_Task_API.csproj
        displayName: 'Restore Packages'

      - script: dotnet build ./TAF_Task_API/TAF_Task_API.csproj --configuration $(buildConfiguration) --no-restore
        displayName: 'Build API Project'

      - script: dotnet test ./TAF_Task_API/TAF_Task_API.csproj --configuration $(buildConfiguration) --no-restore --no-build --logger "trx;LogFileName=test_results.trx"
        displayName: 'Run API Tests'
        
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/*.trx'

      - script: dotnet test ./TAF_Task/TAF_Task.csproj --configuration $(buildConfiguration) --logger "trx;LogFileName=ui_test_results.trx" -e UI_TEST=true -e BROWSER=${{ parameters.browser }}
        displayName: 'Run UI Tests'
        condition: and(succeeded(), ne('${{ parameters.browser }}', ''))
        
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'VSTest'
          testResultsFiles: '**/ui_test_results.trx'

      - upload: '**/screenshots'
        condition: and(succeeded(), ne('${{ parameters.browser }}', ''))
        artifact: Screenshots